// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXystWfblEmSySQcik0I4GF5DjexwM8iE',
    appId: '1:964650887157:web:b5cb25d3dfd070c72f22bc',
    messagingSenderId: '964650887157',
    projectId: 'goldensoft-54e2c',
    authDomain: 'goldensoft-54e2c.firebaseapp.com',
    storageBucket: 'goldensoft-54e2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB35OkRh1pnfWzrLDsEg74AMEgetAF6Yuk',
    appId: '1:964650887157:android:8d47667951e08ded2f22bc',
    messagingSenderId: '964650887157',
    projectId: 'goldensoft-54e2c',
    storageBucket: 'goldensoft-54e2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGaYlRi4K4Q7gaUS2-UGjTBCRjogdCyGc',
    appId: '1:964650887157:ios:7ccbbe4d6a4f78f62f22bc',
    messagingSenderId: '964650887157',
    projectId: 'goldensoft-54e2c',
    storageBucket: 'goldensoft-54e2c.appspot.com',
    iosBundleId: 'com.example.goldesofttest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGaYlRi4K4Q7gaUS2-UGjTBCRjogdCyGc',
    appId: '1:964650887157:ios:7ccbbe4d6a4f78f62f22bc',
    messagingSenderId: '964650887157',
    projectId: 'goldensoft-54e2c',
    storageBucket: 'goldensoft-54e2c.appspot.com',
    iosBundleId: 'com.example.goldesofttest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXystWfblEmSySQcik0I4GF5DjexwM8iE',
    appId: '1:964650887157:web:01eac242e1cbce582f22bc',
    messagingSenderId: '964650887157',
    projectId: 'goldensoft-54e2c',
    authDomain: 'goldensoft-54e2c.firebaseapp.com',
    storageBucket: 'goldensoft-54e2c.appspot.com',
  );
}
